### ISSUE TITLE
lpl-thumbnails-downloader.py on Windows10

### ISSUE THREAD

**Issue by mspykerez** [Mte90/Script#4]
Hi!
How do you make your Thumbnails Downloader script work on windows10?
As an example after placing your lpl-thumbnails-downloader.py file on a folder and run windows powershell from there I've tried to run this command to no avail: "lpl-thumbnails-downloader.py --playlist C:\Users\rsmiguel\Desktop\playlist\scv.lpl"

What am I doing wrong?

**Comment by Mte90** [comment]
I don't know how works shell on windows, I guess that you need to move to the directory, have python installed on your machine and now you can run the script

**Comment by mspykerez** [comment]
Well its not working for me... perhaps something changed on GitHub and needs to be fixed?

When I input this command "lpl-thumbnails-downloader.py --playlist C:\Users\rsmiguel\Desktop\playlist\scv.lpl" it gives the following message: Suggestion [3,General]: The command lpl-thumbnails-downloader.py was not found, but does exist in the current location. Windows PowerShell does not load commands from the current location by default. If you trust this command, instead type: ".\lpl-thumbnails-downloader.py". See "get-help about_Command_Precedence" for more details.

Then I fix the command to .\lpl-thumbnails-downloader.py --playlist C:\Users\rsmiguel\Desktop\playlist\scv.lpl but nothing happens (a black window appears to open for a split second and then it closes).

I assume this script is meant to work on all platforms?

**Comment by Mte90** [comment]
The script works in all the platform but the error is saying that the windows powershell is not founding the script. So for as I know the script is working :-D

You need to insert the path where is the script to execute it, I don't know like C:\myfolder\where\is\the\script. Also probably because is windows require also to specify that need python so the command should be `python C:\myfolder\where\is\the\script\lpl-thumbnails-downloader.py`

**Comment by mspykerez** [comment]
Now is giving me this error:

`  File "C:\Users\rsmiguel\Desktop\playlist\lpl-thumbnails-downloader.py", line 7
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax`

**Comment by Mte90** [comment]
Now found the file but I think that you downloaded instead the html page and not the script.
From https://github.com/Mte90/My-Scripts/blob/master/retroarch/lpl-thumbnails-downloader.py press the Raw button and save that as python file.

**Comment by mspykerez** [comment]
Oh! The script seems to be working now!. I had to make sure that I used " " on the .lpl playlist file if it had spaces so it would not give me an error.

I just have a problem (script doesn't find any matches) with lists that I create with manual scan plus use the option 'Arcade DAT File' on Retroarch so that the names on my list will not appear as the 'jsdkndsnfd.zip' that the Rom file names have (necessary to have the file name match the NAME directive) and instead they will appear named according to the XML file that I provided to Retroarch for the manual scan.
Can this be fixed somehow?

**Comment by Mte90** [comment]
Happy that works now :-D

Can you share to me the lpl with issues? So I can test it?
Right now the way I am doing is getting the rom name and search if the github repo of retroarch has a file with that name, so I need some examples.

**Comment by mspykerez** [comment]
Here you go https://1fichier.com/?126ubuljm5i3vwfn7246

It's a playlist from Epoch - Super Cassette Vision

edit: I think the problem is that when I use the above method described to create a playlist, it kinda uses a different name from the default Rom game files.
For example in the GitHub there is 'Boulder Dash (Japan).png' my entry on playlist is just 'Boulder Dash' and the Rom itself file name is 'bdash.zip'
I think if it ignored what is inside ( ) should do the trick but them the thumbnail will not match the playlist name I dunno.

**Comment by Mte90** [comment]
Renaming the file as `Epoch_-_Super_Cassette_Vision.lpl` will check for this console. 
As I can see any of them exists if I use the name in the repo at https://github.com/libretro-thumbnails/Epoch_-_Super_Cassette_Vision (also there aren't so many thumbnails). 
Sometimes the name don't correspond because the name include ` (Japan)` for retroarch and the script cannot find it.

So I released a new version that try also with adding a country in case don't find them, you need to download again the script.
Of this list can find 19 games, before the change 0.

**Comment by mspykerez** [comment]
Now its downloading something, so I just have to rename the playlists that have a not so self-explanatory game system name to the github entry like you said above and everything should work fine correct ?

I've just tested another playlist "Atari - 2600.lpl" it has a bunch of not founds (not sure if because I have most of my games tagged as Europe and on github says USA) and then it gives this error 
`Traceback (most recent call last):
  File "C:\Users\rsmiguel\Desktop\playlist\lpl-thumbnails-downloader.py", line 107, in <module>
    download_image(folder, console, item['label'], False)
  File "C:\Users\rsmiguel\Desktop\playlist\lpl-thumbnails-downloader.py", line 83, in download_image
    try_game_name = s[1] + ', ' + s[0].replace(', ', '')
IndexError: list index out of range`

**Comment by Mte90** [comment]
Use the filename as a way to detect the console, also because this is the name that a playlist get when using retroarch to generate them. It was the simple way to get retroarch supported from scratch.

Can I have the playlist also for this case?

**Comment by mspykerez** [comment]
Here you go https://1fichier.com/?m8ubml8yzkht9by92ksu

**Comment by Mte90** [comment]
New version with a fix :-)

**Comment by mspykerez** [comment]
Yeh no error now!
I just have a question, since I prefer using (Europe) region and most of the game names listed on libretro repository are (USA) do you think its possible to ignore the mismatch caused by the (USA) or whatever else is inside whatever symbols like ( ) and download them anyway so later it can be renamed accordingly ?

**Comment by Mte90** [comment]
I patched the script, now if not found any with Eruope will try with USA version.

**Comment by mspykerez** [comment]
Doesn't seem to be working as intended... when I get a Europe mismatch it does not try the USA version.

**Comment by Mte90** [comment]
there was a typo and wasn't trying with europe.
I think that now works fine :-)

**Comment by mspykerez** [comment]
Nope! Not working. It's only downloading exact matches. 
I tested with my Atari Playlist I uploaded here https://1fichier.com/?m8ubml8yzkht9by92ksu

edit: it's working with my SCV Playlist I uploaded above here https://1fichier.com/?126ubuljm5i3vwfn7246
The only difference that I can see is that on the SCV the releases are tagged on GitHub as (Japan) and on the playlist they have nothing at all (no Japan, Europe, USA, whatsoever) while on my Atari Playlist when some releases are tagged as USA on GitHub and Europe on the playlist it simple skips the download.

edit2: perhaps the problem is that it's looking for "EUR" when on the playlist its as "Europe"

**Comment by mspykerez** [comment]
Or you simple forgot to update on GitHub page....

**Comment by Mte90** [comment]
You are right I didn't committed on the repo the fix -.-' now is updated.

**Comment by mspykerez** [comment]
WOW its working perfectly! It even auto renames the images right. My only wish is that the process was faster to download... I guess you can open multiple windows at the same time.

What else does the script 'ignore' when searching for a image? for example does it ignore this kinda of stuff "(En,Fr,De)" "(En,Fr,De,Es,It,Nl,Pt,Sv)" "(En,Fr,De,Es,It,Pt,Sv,No)" etc ?

btw is Brazil region supported like Europe and USA ? I appreciate if it was.

**Comment by Mte90** [comment]
I cannot speed up the download, needs to check for every case.
No doesn't ignore anything during download it just try different names for the same game with some rules.
So also brazil or any game name is supported.
